# -*- coding: utf-8 -*-
"""Praktikum3-Visdat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w1TKPgNdcggI7YBl3AjpmxjbrrL0cri-

Kelompok :
- Tria Maulida Sari - 0110222300
- Rahma Dian Nurhikma
- Alma Nur Fajria
"""

import matplotlib.pyplot as plt

# Buat data sample
months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Des']
product_A_sales = [10,20,15,25,30,45,40,50,60,55,65,70]
product_B_sales = [5,10,8,15,18,20,22,30,25,35,40,45]

# Line Plot
plt.plot(months, product_A_sales)
plt.title('Penjualan Produk A Per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Penjualan')
plt.show()

import matplotlib.pyplot as plt

# Menambahkan Multiple Lines
plt.plot(months, product_A_sales, label='Produk A', color='blue', linestyle='--', marker='o')
plt.plot(months, product_B_sales, label='Produk B', color='red', linestyle='--', marker='x')
plt.title("Penjualan Produk Per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Penjualan")
plt.legend()
plt.show()

# Kustomisasi Line Plot
plt.plot(months, product_A_sales, label='Produk A', color='blue', linestyle='--', marker='o')
plt.plot(months, product_B_sales, label='Produk B', color='red', linestyle='--', marker='x')
plt.title("Penjualan Produk Per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Penjualan")
plt.legend()
plt.grid(True)

# Garis berbeda untuk menunjukkan trend
plt.plot(months, product_A_sales, label='Produk A Trend', linestyle='--', color='blue')
plt.plot(months, product_B_sales, label='Produk B Trend', linestyle='--', color='red')
plt.title("Penjualan Produk Per Bulan")
plt.xlabel("Bulan")
plt.ylabel("Jumlah Penjualan")
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt

# Subplot untuk menampilkan beberapa grafik

# Buat data sample
months = ['Jan', 'Feb', 'Mar', 'Apr', 'Mei', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Des']
product_A_sales = [10,20,15,25,30,45,40,50,60,55,65,70]
product_B_sales = [5,10,8,15,18,20,22,30,25,35,40,45]

# Line Plot
fig, axs = plt.subplots(2,1, figsize=(10,8))

# Plot for Product A
axs[0].plot(months, product_A_sales, label='Product A', color='blue', marker='o')
axs[0].set_title('Penjualan Produk A Per Bulan')
axs[0].set_xlabel('Bulan')
axs[0].set_ylabel('Jumlah Penjualan')
axs[0].legend()
axs[0].grid(True)

# Plot for Product B
axs[1].plot(months, product_B_sales, label='Product B', color='red', marker='x')
axs[1].set_title('Penjualan Produk B Per Bulan')
axs[1].set_xlabel('Bulan')
axs[1].set_ylabel('Jumlah Penjualan')
axs[1].legend()
axs[1].grid(True)

plt.tight_layout()
plt.show()